spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: softieStudent
    password: Softie12345
    url: "jdbc:mysql://localhost:3306/project_shop_rtv?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false"
  jpa:
    database-platform: "org.hibernate.dialect.MySQL8Dialect"
  liquibase:
    change-log: "classpath:/liquibase/liquibase-changeLog.xml"
  application:
    name: order-service
server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    preferIpAddress: true